# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
name: Compare artifacts

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Generate the artifact for this build
      - name: Build artifact
        run: echo "$GITHUB_RUN_NUMBER" > test-artifact.txt

      # Download the base artifact using this action
      - uses: andrewiggins/download-base-artifact@v1
        with:
          artifact: "test-artifact.txt"
          path: base

      # Compare the two artifacts as you wish
      - run: diff test-artifact.txt base/test-artifact.txt
